### ISSUE TITLE
Integrate Algolia search

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/docs#337] opened 2023-04-10 21:12 UTC
[docs.stacks.co](https://docs.stacks.co/docs/intro) 

cmd+k

![Image](https://github.com/hirosystems/docs/assets/55154433/f96edbf0-3e82-4b67-87ef-88db24fc463f)

References:
https://www.algolia.com/developers/
https://github.com/stacks-network/docs/pull/1463/files

Ping @Charlie to resolve the API key and API ID from the env variables.

**Comment by janniks** [comment] 2023-04-10 21:14
Are we  unhappy with the local search?

**Comment by LakshmiLavanyaKasturi** [comment] 2023-06-20 16:58
Requested snippet/access info to integrate with our docs: https://docsearch.algolia.com/apply/

**Comment by LakshmiLavanyaKasturi** [comment] 2023-07-10 20:00
@tortiz-hs is trying to get support from the Algolia team as the 2-factor authentication doesn't work. 

Once we figure this out, I will go ahead and use the index name given by the Algolia team and instantiate crawls using crawler.algolia.com (suggested by Kenny Rogers from the foundation).

**Comment by LakshmiLavanyaKasturi** [comment] 2023-07-24 22:12
@CharlieC3 Assigning this issue as I am blocked by https://github.com/hirosystems/devops/issues/1274. Please assign it back to me once the issue is resolved. Thanks!

**Comment by CharlieC3** [comment] 2023-07-25 03:18
@LakshmiLavanyaKasturi we should mark this issue as blocked instead. Dean is working on the related issue.

**Comment by LakshmiLavanyaKasturi** [comment] 2023-08-15 20:29
After the conversation with Kenny from the foundation, the following is the summary:

- We can create an Algolia crawler without Netlify. 
- Apply to the DocSearch program [apply to the program](https://docsearch.algolia.com/apply) and get the APP ID, indexName, and the APIKey.
-  Use the above details to create a crawler.

**Comment by LakshmiLavanyaKasturi** [comment] 2023-08-31 15:44
PR: https://github.com/hirosystems/docs/pull/427 is ready for review.

**Comment by mefrem** [comment] 2023-10-04 22:20
Yep! Closed with https://github.com/hirosystems/docs/pull/427

**Closed by mefrem** 2023-10-04 22:20 UTC
Labels: enhancement
