### ISSUE TITLE
Build automation tools for new Hiro docs site

### ISSUE THREAD

**Issue by trichards-hiro** [hirosystems/docs#181] opened 2022-10-04 18:46 UTC
As we build out the new docs site, we need to determine how we can dynamically pull content from other GitHub repos into our docs.

For example, we want to "pull" code snippets and examples from a GitHub repository, and not manually copy-and-paste these code samples on the page, requiring continuous maintenance and review to ensure the code snippets and examples are up-to-date.

**Comment by LakshmiLavanyaKasturi** [comment] 2023-07-21 20:32
This is the duplicate of https://github.com/hirosystems/docs/issues/366

**Closed by LakshmiLavanyaKasturi** 2023-07-21 20:32 UTC
