### ISSUE TITLE
Write Deprecation Policy page for our docs

### ISSUE THREAD

**Issue by trichards-hiro** [hirosystems/docs#193] opened 2022-10-12 19:02 UTC
We do not currently tell users what our deprecation policy is in our docs. This is a requirement for users, and we should try to explicitly state what our deprecation policy should be moving forward.

**Comment by LakshmiLavanyaKasturi** [comment] 2023-09-05 17:13
Duplicate of https://github.com/hirosystems/docs/issues/260

**Closed by LakshmiLavanyaKasturi** 2023-09-05 17:13 UTC
Labels: enhancement, docathon
